import { createContext, useState } from "react";


const BlogContext = createContext(null);


const BlogProvider = ({ children }) => {

    const [blogs] = useState([
      {
        "id": 1,
        "category": "Waste Renewal",
        "title": "The Future of Waste Renewal: Turning Trash into Treasure",
        "description": "Waste renewal is the process of converting waste materials into reusable products. This blog explores innovative technologies like pyrolysis and anaerobic digestion that are revolutionizing waste management. Learn how waste renewal can reduce landfill dependency, create renewable energy, and contribute to a circular economy.",
        "content": "Waste renewal is more than just recycling—it's about transforming waste into valuable resources. Technologies like pyrolysis convert plastic waste into fuel, reducing landfill waste and dependence on fossil fuels. Anaerobic digestion, on the other hand, uses organic waste to generate biogas, a renewable energy source. These innovations not only help the environment but also create economic opportunities by turning waste into marketable products. With growing environmental concerns, industries are investing in sustainable waste management strategies. The future of waste renewal lies in technological advancements, community participation, and government policies promoting a circular economy.",
        "image": "../../Components/images/renewal.png",
        "author": {
          "name": "Ayush Ranjan",
          "date": "10 Oct 2023",
          "avatar": ""
        }
      },
      {
        "id": 2,
        "category": "Recycling",
        "title": "5 Simple Steps to Start Recycling at Home",
        "description": "Recycling doesn’t have to be complicated! This guide walks you through 5 easy steps to start recycling at home, from sorting your waste to finding local recycling centers. Discover how small changes in your daily routine can make a big impact on the environment.",
        "image": "../../Components/images/recycling_tips.png",
        "author": {
          "name": "Rohit Khallar",
          "date": "15 Sep 2023",
          "avatar": ""

        }
      },
      {
        "id": 3,
        "category": "E-Waste",
        "title": "The Hidden Dangers of E-Waste and How to Dispose of It Safely",
        "description": "Electronic waste is one of the fastest-growing waste streams globally. This blog highlights the environmental and health risks of improper e-waste disposal and provides practical tips on how to recycle your old gadgets responsibly. Learn about certified e-waste recycling centers near you.",
        "image": "../../Components/images/ewaste_dangers.png",
        "author": {
          "name": "Ayush Kumar",
          "date": "20 Aug 2023",
          "avatar": ""
        }
      },
      {
        "id": 4,
        "category": "Scrap Workers",
        "title": "The Unsung Heroes: The Role of Scrap Workers in Waste Management",
        "description": "Scrap workers play a crucial role in waste management by collecting, sorting, and recycling materials that would otherwise end up in landfills. This blog sheds light on their contributions, challenges, and how we can support their efforts for a cleaner planet.",
        "image": "../../Components/images/scrapworkers.png",
        "author": {
          "name": "Tanisha Rattan",
          "date": "25 Jul 2023",
          "avatar": ""
        }
      },
      {
        "id": 5,
        "category": "Scrap Recycling Industries",
        "title": "How Scrap Recycling Industries Are Driving the Circular Economy",
        "description": "Scrap recycling industries are at the forefront of the circular economy, turning waste into valuable resources. This blog explores how these industries operate, the technologies they use, and their impact on reducing carbon emissions and conserving natural resources.",
        "image": "../../Components/images/RecycleCT.png",
        "author": {
          "name": "Ayush Kumar",
          "date": "30 Jun 2023",
          "avatar": ""
        }
      },
      {
        "id": 6,
        "category": "Recycling Education",
        "title": "Teaching Kids About Recycling: Fun and Educational Activities",
        "description": "Educating the next generation about recycling is essential for a sustainable future. This blog provides fun and engaging activities to teach kids about recycling, from DIY crafts to interactive games. Help your children become eco-conscious citizens!",
        "image": "../../Components/images/Education.png",
        "author": {
          "name": "Ayush Ranjan",
          "date": "05 May 2023",
          "avatar": ""
        }
      },
      {
        "id": 7,
        "category": "Carbon Footprints",
        "title": "Understanding Carbon Footprints: How to Measure and Reduce Yours",
        "description": "Your carbon footprint is the total amount of greenhouse gases, primarily carbon dioxide, generated by your actions. From transportation and energy use to food consumption and waste, every choice you make contributes to your carbon footprint. This blog explains how to calculate your carbon footprint using online tools and provides practical tips to reduce it. Learn how small changes, like switching to renewable energy, reducing meat consumption, and using public transport, can make a big difference. Join the movement to combat climate change by taking responsibility for your carbon emissions today.",
        "image": "../../Components/images/Carbon.png",
        "author": {
          "name": "Rohit Khallar",
          "date": "18 May 2023",
          "avatar": "/images/eco_advocate_avatar.jpg"
        }
      },
      {
        "id": 8,
        "category": "Transportation",
        "title": "Sustainable Transportation: How to Reduce Your Commute's Carbon Impact",
        "description": "Transportation is one of the largest contributors to carbon emissions worldwide. This blog explores sustainable transportation options, from electric vehicles and public transit to cycling and carpooling. Learn how to reduce your commute's carbon impact by making smarter choices, planning efficient routes, and advocating for greener infrastructure. Discover how small changes in your daily travel habits can lead to a significant reduction in your carbon footprint and contribute to a healthier planet.",
        "image": "../../Components/images/trans.png",
        "author": {
          "name": "Green Commuter",
          "date": "25 Jun 2023",
          "avatar": "/images/green_commuter_avatar.jpg"
        }
      },
      {
        "id": 9,
        "category": "Sustainability",
        "title": "Upcycling: Transforming Waste into Creative Treasures",
        "description": "Upcycling is the art of transforming discarded materials into new, functional, and beautiful products. Unlike recycling, which breaks down materials, upcycling gives waste a second life without degrading its quality. In this blog, we explore inspiring upcycling ideas, from turning old jars into stylish planters to crafting furniture from pallets. Learn how upcycling not only reduces waste but also fosters creativity and promotes a sustainable lifestyle. Whether you're a DIY enthusiast or just starting, this guide will inspire you to see waste in a whole new light.",
        "image": "../../Components/images/Sustainabillity.png",
        "author": {
          "name": "Rohit Khallar",
          "date": "28 Mar 2023",
          "avatar": "/images/creative_eco_avatar.jpg"
        }
      }
    ])
    
    
  

  return <BlogContext.Provider value={{ blogs }}>{children}</BlogContext.Provider>;
};

export { BlogContext, BlogProvider };





